# -*- coding: utf-8 -*-
"""
Slovar besed za jezikovni kviz.

Struktura vsakega vnosa:
    (slovensko, italijansko, špansko, angleško)

Skupine:
 1 - glagoli (osnovne oblike)
 2 - glagoli v spregatvah (sedanjik)
 3 - pridevniki
 4 - hrana
 5 - družina in sorodstvene vezi
 6 - predlogi
 7 - čas (dni, meseci, letni časi, ...)
 8 - različne pogoste besede
"""

# 1) GLAGOLI – 100 osnovnih glagolov
VERBS = [
    # 1–10
    ("biti", "essere", "ser", "to be"),
    ("imeti", "avere", "tener", "to have"),
    ("delati", "lavorare", "trabajar", "to work"),
    ("iti", "andare", "ir", "to go"),
    ("reči", "dire", "decir", "to say"),
    ("videti", "vedere", "ver", "to see"),
    ("jesti", "mangiare", "comer", "to eat"),
    ("piti", "bere", "beber", "to drink"),
    ("hoteti", "volere", "querer", "to want"),
    ("dati", "dare", "dar", "to give"),

    # 11–20
    ("priti", "venire", "venir", "to come"),
    ("vedeti", "sapere", "saber", "to know"),
    ("misliti", "pensare", "pensar", "to think"),
    ("vzeti", "prendere", "tomar", "to take"),
    ("najti", "trovare", "encontrar", "to find"),
    ("čutiti", "sentire", "sentir", "to feel"),
    ("uporabljati", "usare", "usar", "to use"),
    ("delovati", "funzionare", "funcionar", "to function"),
    ("ostati", "restare", "quedar", "to stay"),
    ("verjeti", "credere", "creer", "to believe"),

    # 21–30
    ("govoriti", "parlare", "hablar", "to speak"),
    ("slišati", "sentire", "oír", "to hear"),
    ("živeti", "vivere", "vivir", "to live"),
    ("deliti", "condividere", "compartir", "to share"),
    ("poskušati", "provare", "intentar", "to try"),
    ("odpreti", "aprire", "abrir", "to open"),
    ("zapreti", "chiudere", "cerrar", "to close"),
    ("začeti", "iniziare", "empezar", "to start"),
    ("končati", "finire", "terminar", "to finish"),
    ("spati", "dormire", "dormir", "to sleep"),

    # 31–40
    ("voziti", "guidare", "conducir", "to drive"),
    ("brati", "leggere", "leer", "to read"),
    ("pisati", "scrivere", "escribir", "to write"),
    ("kupiti", "comprare", "comprar", "to buy"),
    ("prodati", "vendere", "vender", "to sell"),
    ("pomagati", "aiutare", "ayudar", "to help"),
    ("igrati", "giocare", "jugar", "to play"),
    ("teči", "correre", "correr", "to run"),
    ("hoditi", "camminare", "caminar", "to walk"),
    ("plačati", "pagare", "pagar", "to pay"),

    # 41–50
    ("zapomniti si", "ricordare", "recordar", "to remember"),
    ("pozabiti", "dimenticare", "olvidar", "to forget"),
    ("poslati", "mandare", "enviar", "to send"),
    ("prejeti", "ricevere", "recibir", "to receive"),
    ("odločiti se", "decidere", "decidir", "to decide"),
    ("vprašati", "chiedere", "preguntar", "to ask"),
    ("odgovoriti", "rispondere", "responder", "to answer"),
    ("čakati", "aspettare", "esperar", "to wait"),
    ("potrebovati", "bisognare", "necesitar", "to need"),
    ("razumeti", "capire", "entender", "to understand"),

    # 51–60
    ("učiti se", "imparare", "aprender", "to learn"),
    ("učiti", "insegnare", "enseñar", "to teach"),
    ("poslušati", "ascoltare", "escuchar", "to listen"),
    ("gledati", "guardare", "mirar", "to watch"),
    ("čistiti", "pulire", "limpiar", "to clean"),
    ("kuhati", "cucinare", "cocinar", "to cook"),
    ("plesati", "ballare", "bailar", "to dance"),
    ("plavati", "nuotare", "nadar", "to swim"),
    ("potovati", "viaggiare", "viajar", "to travel"),
    ("leteti", "volare", "volar", "to fly"),

    # 61–70
    ("kupovati", "fare la spesa", "hacer la compra", "to shop"),
    ("organizirati", "organizzare", "organizar", "to organize"),
    ("načrtovati", "pianificare", "planear", "to plan"),
    ("prižgati", "accendere", "encender", "to turn on"),
    ("ugasniti", "spegnere", "apagar", "to turn off"),
    ("pomivati", "lavare", "lavar", "to wash"),
    ("brskati", "navigare", "navegar", "to browse"),
    ("poklicati", "chiamare", "llamar", "to call"),
    ("srečati", "incontrare", "encontrar", "to meet"),
    ("risati", "disegnare", "dibujar", "to draw"),

    # 71–80
    ("slikati", "dipingere", "pintar", "to paint"),
    ("peti", "cantare", "cantar", "to sing"),
    ("voziti kolo", "andare in bicicletta", "ir en bici", "to ride a bike"),
    ("parkirati", "parcheggiare", "aparcar", "to park"),
    ("pripraviti", "preparare", "preparar", "to prepare"),
    ("pospraviti", "riordinare", "ordenar", "to tidy up"),
    ("spoznati", "conoscere", "conocer", "to get to know"),
    ("voziti se", "viaggiare", "viajar", "to ride"),
    ("odložiti", "posare", "dejar", "to put down"),
    ("dvigniti", "alzare", "levantar", "to lift"),

    # 81–90
    ("obrati", "raccogliere", "recoger", "to pick"),
    ("saditi", "piantare", "plantar", "to plant"),
    ("sejati", "seminare", "sembrar", "to sow"),
    ("zalivati", "innaffiare", "regar", "to water"),
    ("posušiti", "asciugare", "secar", "to dry"),
    ("graditi", "costruire", "construir", "to build"),
    ("rušiti", "demolire", "demoler", "to demolish"),
    ("šivati", "cucire", "coser", "to sew"),
    ("plesti", "lavorare a maglia", "tejer", "to knit"),
    ("računati", "calcolare", "calcular", "to calculate"),

    # 91–100
    ("razlagati", "spiegare", "explicar", "to explain"),
    ("raziskovati", "ricercare", "investigar", "to research"),
    ("pretiravati", "esagerare", "exagerar", "to exaggerate"),
    ("odločati", "decidere", "decidir", "to decide (ongoing)"),
    ("sprejeti", "accettare", "aceptar", "to accept"),
    ("zavrniti", "rifiutare", "rechazar", "to refuse"),
    ("upati", "sperare", "esperar", "to hope"),
    ("sanjati", "sognare", "soñar", "to dream"),
    ("smejati se", "ridere", "reírse", "to laugh"),
    ("jokati", "piangere", "llorar", "to cry"),
]


# 2) GLAGOLI V SPREGATVAH – 30 vrstic (biti, imeti, iti, delati)
VERB_CONJ = [
    # biti
    ("jaz sem", "io sono", "yo soy", "I am"),
    ("ti si", "tu sei", "tú eres", "you are"),
    ("on je", "lui è", "él es", "he is"),
    ("ona je", "lei è", "ella es", "she is"),
    ("mi smo", "noi siamo", "nosotros somos", "we are"),
    ("vi ste", "voi siete", "vosotros sois", "you are (pl.)"),
    ("oni so", "loro sono", "ellos son", "they are"),

    # imeti
    ("jaz imam", "io ho", "yo tengo", "I have"),
    ("ti imaš", "tu hai", "tú tienes", "you have"),
    ("on ima", "lui ha", "él tiene", "he has"),
    ("ona ima", "lei ha", "ella tiene", "she has"),
    ("mi imamo", "noi abbiamo", "nosotros tenemos", "we have"),
    ("vi imate", "voi avete", "vosotros tenéis", "you have (pl.)"),
    ("oni imajo", "loro hanno", "ellos tienen", "they have"),

    # iti
    ("jaz grem", "io vado", "yo voy", "I go"),
    ("ti greš", "tu vai", "tú vas", "you go"),
    ("on gre", "lui va", "él va", "he goes"),
    ("ona gre", "lei va", "ella va", "she goes"),
    ("mi gremo", "noi andiamo", "nosotros vamos", "we go"),
    ("vi greste", "voi andate", "vosotros vais", "you go (pl.)"),
    ("oni gredo", "loro vanno", "ellos van", "they go"),

    # delati
    ("jaz delam", "io lavoro", "yo trabajo", "I work"),
    ("ti delaš", "tu lavori", "tú trabajas", "you work"),
    ("on dela", "lui lavora", "él trabaja", "he works"),
    ("ona dela", "lei lavora", "ella trabaja", "she works"),
    ("mi delamo", "noi lavoriamo", "nosotros trabajamos", "we work"),
    ("vi delate", "voi lavorate", "vosotros trabajáis", "you work (pl.)"),
    ("oni delajo", "loro lavorano", "ellos trabajan", "they work"),

    # dodatni dve ponovitvi (da je skupaj 30)
    ("jaz sem", "io sono", "yo soy", "I am"),
    ("jaz imam", "io ho", "yo tengo", "I have"),
]


# 3) PRIDEVNIKI – lahko jih kasneje tudi razširiš
ADJECTIVES = [
    ("dober", "buono", "bueno", "good"),
    ("slab", "cattivo", "malo", "bad"),
    ("velik", "grande", "grande", "big"),
    ("majhen", "piccolo", "pequeño", "small"),
    ("nov", "nuovo", "nuevo", "new"),
    ("star", "vecchio", "viejo", "old"),
    ("lep", "bello", "bonito", "beautiful"),
    ("grd", "brutto", "feo", "ugly"),
    ("drag", "caro", "caro", "expensive"),
    ("počasni", "lento", "lento", "slow"),
    ("hiter", "veloce", "rápido", "fast"),
    ("topel", "caldo", "caliente", "warm"),
    ("hladen", "freddo", "frío", "cold"),
    ("lačen", "affamato", "hambriento", "hungry"),
    ("žejen", "assetato", "sediento", "thirsty"),
    ("vesel", "felice", "feliz", "happy"),
    ("žalosten", "triste", "triste", "sad"),
    ("utrujen", "stanco", "cansado", "tired"),
    ("zanimiv", "interessante", "interesante", "interesting"),
    ("dolgočasen", "noioso", "aburrido", "boring"),
]


# 4) HRANA – 150 besed
FOOD = [
    # osnovno
    ("kruh", "pane", "pan", "bread"),
    ("maslo", "burro", "mantequilla", "butter"),
    ("sir", "formaggio", "queso", "cheese"),
    ("mleko", "latte", "leche", "milk"),
    ("jajce", "uovo", "huevo", "egg"),
    ("meso", "carne", "carne", "meat"),
    ("riba", "pesce", "pescado", "fish"),
    ("sadje", "frutta", "fruta", "fruit"),
    ("zelenjava", "verdura", "verdura", "vegetables"),
    ("sladoled", "gelato", "helado", "ice cream"),
    ("juha", "zuppa", "sopa", "soup"),
    ("kava", "caffè", "café", "coffee"),
    ("čaj", "tè", "té", "tea"),
    ("voda", "acqua", "agua", "water"),
    ("vino", "vino", "vino", "wine"),
    ("pivo", "birra", "cerveza", "beer"),
    ("sladkor", "zucchero", "azúcar", "sugar"),
    ("sol", "sale", "sal", "salt"),
    ("poper", "pepe", "pimienta", "pepper"),
    ("testenine", "pasta", "pasta", "pasta"),

    # sadje
    ("jabolko", "mela", "manzana", "apple"),
    ("hruška", "pera", "pera", "pear"),
    ("banana", "banana", "plátano", "banana"),
    ("pomaranča", "arancia", "naranja", "orange"),
    ("limona", "limone", "limón", "lemon"),
    ("breskev", "pesca", "melocotón", "peach"),
    ("marelica", "albicocca", "albaricoque", "apricot"),
    ("sliva", "prugna", "ciruela", "plum"),
    ("češnja", "ciliegia", "cereza", "cherry"),
    ("jagoda", "fragola", "fresa", "strawberry"),
    ("malina", "lampone", "frambuesa", "raspberry"),
    ("borovnica", "mirtillo", "arándano", "blueberry"),
    ("lubenica", "anguria", "sandía", "watermelon"),
    ("melona", "melone", "melón", "melon"),
    ("kivi", "kiwi", "kiwi", "kiwi"),
    ("ananas", "ananas", "piña", "pineapple"),
    ("grozdje", "uva", "uva", "grapes"),
    ("figa", "fico", "higo", "fig"),
    ("grenivka", "pompelmo", "pomelo", "grapefruit"),
    ("mandarina", "mandarino", "mandarina", "mandarin"),

    # zelenjava
    ("krompir", "patata", "patata", "potato"),
    ("korenček", "carota", "zanahoria", "carrot"),
    ("čebula", "cipolla", "cebolla", "onion"),
    ("česen", "aglio", "ajo", "garlic"),
    ("paradižnik", "pomodoro", "tomate", "tomato"),
    ("paprika", "peperone", "pimiento", "pepper"),
    ("kumara", "cetriolo", "pepino", "cucumber"),
    ("solata", "insalata", "ensalada", "lettuce"),
    ("špinača", "spinaci", "espinaca", "spinach"),
    ("zelje", "cavolo", "col", "cabbage"),
    ("brokoli", "broccoli", "brócoli", "broccoli"),
    ("cvetača", "cavolfiore", "coliflor", "cauliflower"),
    ("buča", "zucca", "calabaza", "pumpkin"),
    ("bučka", "zucchina", "calabacín", "zucchini"),
    ("rdeča pesa", "barbabietola", "remolacha", "beetroot"),
    ("por", "porro", "puerro", "leek"),
    ("grah", "piselli", "guisantes", "peas"),
    ("fižol", "fagioli", "alubias", "beans"),
    ("leča", "lenticchie", "lentejas", "lentils"),
    ("čičerika", "ceci", "garbanzos", "chickpeas"),
    ("artičoka", "carciofo", "alcachofa", "artichoke"),
    ("rdeča pesa list", "bietola", "acelga", "chard"),
    ("radič", "radicchio", "radicchio", "radicchio"),
    ("čili", "peperoncino", "chile", "chili"),
    ("goba", "fungo", "seta", "mushroom"),
    ("šampinjon", "champignon", "champiñón", "champignon"),
    ("olive", "olive", "aceitunas", "olives"),
    ("kapre", "capperi", "alcaparras", "capers"),
    ("koruza", "mais", "maíz", "corn"),
    ("rukola", "rucola", "rúcula", "arugula"),

    # žita in kruhi
    ("riž", "riso", "arroz", "rice"),
    ("pšenica", "grano", "trigo", "wheat"),
    ("ovseni kosmiči", "fiocchi d'avena", "copos de avena", "oat flakes"),
    ("koruzni kosmiči", "cornflakes", "copos de maíz", "cornflakes"),
    ("špageti", "spaghetti", "espaguetis", "spaghetti"),
    ("rezanci", "tagliatelle", "tallarines", "noodles"),
    ("rižota", "risotto", "risotto", "risotto"),
    ("pica", "pizza", "pizza", "pizza"),
    ("polenta", "polenta", "polenta", "polenta"),
    ("kruh z žiti", "pane ai cereali", "pan integral", "wholegrain bread"),
    ("žemlja", "panino", "bollo", "bread roll"),
    ("bageta", "baguette", "baguette", "baguette"),
    ("tortilja", "tortilla", "tortilla", "tortilla"),
    ("pita kruh", "pane pita", "pan de pita", "pita bread"),
    ("kroasan", "cornetto", "cruasán", "croissant"),
    ("keks", "biscotto", "galleta", "biscuit"),
    ("piškot", "biscotto", "galleta", "cookie"),
    ("torta", "torta", "tarta", "cake"),
    ("kolač", "dolce", "pastel", "pastry"),
    ("palačinka", "crêpe", "crepe", "pancake"),

    # mlečni izdelki
    ("jogurt", "yogurt", "yogur", "yoghurt"),
    ("smetana", "panna", "nata", "cream"),
    ("skuta", "ricotta", "requesón", "cottage cheese"),
    ("slan sir", "feta", "queso feta", "feta"),
    ("margarina", "margarina", "margarina", "margarine"),
    ("sirna plošča", "tagliere di formaggi", "tabla de quesos", "cheese platter"),
    ("mascarpone", "mascarpone", "mascarpone", "mascarpone"),
    ("parmezan", "parmigiano", "parmesano", "parmesan"),
    ("mozzarella", "mozzarella", "mozzarella", "mozzarella"),

    # meso in ribe
    ("govedina", "manzo", "ternera", "beef"),
    ("svinjina", "maiale", "cerdo", "pork"),
    ("piščanec", "pollo", "pollo", "chicken"),
    ("puran", "tacchino", "pavo", "turkey"),
    ("jagnjetina", "agnello", "cordero", "lamb"),
    ("klobasa", "salsiccia", "salchicha", "sausage"),
    ("šunka", "prosciutto", "jamón", "ham"),
    ("slanik", "aringa", "arenque", "herring"),
    ("losos", "salmone", "salmón", "salmon"),
    ("tuna", "tonno", "atún", "tuna"),
    ("sardina", "sardina", "sardina", "sardine"),
    ("rakci", "gamberetti", "gambas", "shrimp"),
    ("lignji", "calamari", "calamares", "squid"),
    ("školjke", "cozze", "mejillones", "mussels"),
    ("pršut", "prosciutto crudo", "jamón curado", "dry-cured ham"),
    ("salama", "salame", "salchichón", "salami"),
    ("pašteta", "paté", "paté", "pâté"),
    ("čevapčiči", "ćevapčići", "ćevapčići", "cevapi"),
    ("burger", "hamburger", "hamburguesa", "burger"),
    ("zrezek", "bistecca", "bistec", "steak"),

    # dodatki, omake, začimbe
    ("majoneza", "maionese", "mayonesa", "mayonnaise"),
    ("gorčica", "senape", "mostaza", "mustard"),
    ("kečap", "ketchup", "kétchup", "ketchup"),
    ("oljčno olje", "olio d'oliva", "aceite de oliva", "olive oil"),
    ("rastlinsko olje", "olio di semi", "aceite vegetal", "vegetable oil"),
    ("kis", "aceto", "vinagre", "vinegar"),
    ("omaka", "salsa", "salsa", "sauce"),
    ("paradižnikova omaka", "sugo di pomodoro", "salsa de tomate", "tomato sauce"),
    ("sojina omaka", "salsa di soia", "salsa de soja", "soy sauce"),
    ("čili omaka", "salsa piccante", "salsa picante", "hot sauce"),

    # sladice in prigrizki
    ("čokolada", "cioccolato", "chocolate", "chocolate"),
    ("bonbon", "caramella", "caramelo", "candy"),
    ("čips", "patatine", "patatas fritas", "chips"),
    ("oreški", "noci", "nueces", "nuts"),
    ("mandlji", "mandorle", "almendras", "almonds"),
    ("lešniki", "nocciole", "avellanas", "hazelnuts"),
    ("pistacije", "pistacchi", "pistachos", "pistachios"),
    ("rozine", "uvette", "pasas", "raisins"),
    ("med", "miele", "miel", "honey"),
    ("piškoti", "biscotti", "galletas", "cookies"),

    # jedi
    ("sendvič", "panino imbottito", "bocadillo", "sandwich"),
    ("solata (jed)", "insalata mista", "ensalada mixta", "mixed salad"),
    ("golaž", "gulasch", "goulash", "goulash"),
    ("enolončnica", "minestra", "cocido", "stew"),
    ("pražen krompir", "patate arrosto", "patatas asadas", "roast potatoes"),
    ("pire krompir", "purè di patate", "puré de patata", "mashed potatoes"),
    ("ocvrt krompirček", "patatine fritte", "patatas fritas", "french fries"),
    ("omleta", "frittata", "tortilla francesa", "omelette"),
    ("zajtrk", "colazione", "desayuno", "breakfast"),
    ("kosilo", "pranzo", "almuerzo", "lunch"),
    ("večerja", "cena", "cena", "dinner"),
]


# 5) DRUŽINA IN SORODSTVO – razširjeno
FAMILY = [
    ("oče", "padre", "padre", "father"),
    ("mati", "madre", "madre", "mother"),
    ("starš", "genitore", "progenitor", "parent"),
    ("sin", "figlio", "hijo", "son"),
    ("hči", "figlia", "hija", "daughter"),
    ("brat", "fratello", "hermano", "brother"),
    ("sestra", "sorella", "hermana", "sister"),
    ("dedek", "nonno", "abuelo", "grandfather"),
    ("babica", "nonna", "abuela", "grandmother"),
    ("pradedek", "bisnonno", "bisabuelo", "great-grandfather"),
    ("prababica", "bisnonna", "bisabuela", "great-grandmother"),
    ("vnuk", "nipote", "nieto", "grandson"),
    ("vnukinja", "nipote", "nieta", "granddaughter"),
    ("vnuki", "nipoti", "nietos", "grandchildren"),
    ("stric", "zio", "tío", "uncle"),
    ("teta", "zia", "tía", "aunt"),
    ("nečak", "nipote", "sobrino", "nephew"),
    ("nečakinja", "nipote", "sobrina", "niece"),
    ("bratranec", "cugino", "primo", "cousin"),
    ("sestrična", "cugina", "prima", "cousin"),
    ("mož", "marito", "esposo", "husband"),
    ("žena", "moglie", "esposa", "wife"),
    ("partner", "partner", "pareja", "partner"),
    ("zaročenec", "fidanzato", "prometido", "fiancé"),
    ("zaročenka", "fidanzata", "prometida", "fiancée"),
    ("otrok", "bambino", "niño", "child"),
    ("star starš", "nonno", "abuelo", "grandparent"),
    ("tašča", "suocera", "suegra", "mother-in-law"),
    ("tast", "suocero", "suegro", "father-in-law"),
    ("snaha", "nuora", "nuera", "daughter-in-law"),
    ("zet", "genero", "yerno", "son-in-law"),
    ("svak", "cognato", "cuñado", "brother-in-law"),
    ("svakinja", "cognata", "cuñada", "sister-in-law"),
    ("pastorek", "figliastro", "hijastro", "stepson"),
    ("pastorka", "figliastra", "hijastra", "stepdaughter"),
    ("mačeha", "matrigna", "madrastra", "stepmother"),
    ("očim", "patrigno", "padrastro", "stepfather"),
    ("posvojen otrok", "figlio adottivo", "hijo adoptivo", "adopted child"),
]


# 6) PREDLOGI
PREPOSITIONS = [
    ("na", "su", "en", "on"),
    ("v", "in", "en", "in"),
    ("pod", "sotto", "debajo de", "under"),
    ("nad", "sopra", "sobre", "above"),
    ("pred", "davanti a", "delante de", "in front of"),
    ("za", "dietro", "detrás de", "behind"),
    ("med", "tra", "entre", "between"),
    ("z", "con", "con", "with"),
    ("brez", "senza", "sin", "without"),
    ("do", "fino a", "hasta", "until/to"),
    ("od", "da", "desde", "from/since"),
    ("pri", "presso", "junto a", "at/near"),
]


# 7) ČAS – dnevi, meseci, letni časi, osnovne časovne besede
TIME_WORDS = [
    ("dan", "giorno", "día", "day"),
    ("noč", "notte", "noche", "night"),
    ("jutro", "mattina", "mañana", "morning"),
    ("popoldne", "pomeriggio", "tarde", "afternoon"),
    ("večer", "sera", "noche", "evening"),

    ("ponedeljek", "lunedì", "lunes", "Monday"),
    ("torek", "martedì", "martes", "Tuesday"),
    ("sreda", "mercoledì", "miércoles", "Wednesday"),
    ("četrtek", "giovedì", "jueves", "Thursday"),
    ("petek", "venerdì", "viernes", "Friday"),
    ("sobota", "sabato", "sábado", "Saturday"),
    ("nedelja", "domenica", "domingo", "Sunday"),

    ("januar", "gennaio", "enero", "January"),
    ("februar", "febbraio", "febrero", "February"),
    ("marec", "marzo", "marzo", "March"),
    ("april", "aprile", "abril", "April"),
    ("maj", "maggio", "mayo", "May"),
    ("junij", "giugno", "junio", "June"),
    ("julij", "luglio", "julio", "July"),
    ("avgust", "agosto", "agosto", "August"),
    ("september", "settembre", "septiembre", "September"),
    ("oktober", "ottobre", "octubre", "October"),
    ("november", "novembre", "noviembre", "November"),
    ("december", "dicembre", "diciembre", "December"),

    ("pomlad", "primavera", "primavera", "spring"),
    ("poletje", "estate", "verano", "summer"),
    ("jesen", "autunno", "otoño", "autumn"),
    ("zima", "inverno", "invierno", "winter"),

    ("danes", "oggi", "hoy", "today"),
    ("včeraj", "ieri", "ayer", "yesterday"),
    ("jutri", "domani", "mañana", "tomorrow"),
    ("zdaj", "adesso", "ahora", "now"),
    ("pozneje", "più tardi", "más tarde", "later"),
    ("prej", "prima", "antes", "before"),
]


# 8) POGOSTE BESEDE – 150, slovenska beseda ima >4 črke
COMMON_WORDS = [
    ("vedno", "sempre", "siempre", "always"),
    ("nikoli", "mai", "nunca", "never"),
    ("mogoče", "forse", "quizás", "maybe"),
    ("zatorej", "dunque", "por lo tanto", "therefore"),
    ("potem", "poi", "luego", "then"),
    ("najprej", "prima", "primero", "first"),
    ("skupaj", "insieme", "juntos", "together"),
    ("počasi", "piano", "despacio", "slowly"),
    ("hitro", "velocemente", "rápido", "quickly"),
    ("resnično", "davvero", "realmente", "really"),
    ("približno", "circa", "aproximadamente", "approximately"),
    ("pogosto", "spesso", "a menudo", "often"),
    ("redko", "raramente", "raramente", "rarely"),
    ("včasih", "a volte", "a veces", "sometimes"),
    ("posebej", "specialmente", "especialmente", "especially"),
    ("skoraj", "quasi", "casi", "almost"),
    ("drugič", "un'altra volta", "otra vez", "another time"),
    ("jutrišnji", "di domani", "de mañana", "tomorrow's"),
    ("včerajšnji", "di ieri", "de ayer", "yesterday's"),
    ("današnji", "odierno", "de hoy", "today's"),
    ("vsakdanji", "quotidiano", "cotidiano", "everyday"),
    ("pomemben", "importante", "importante", "important"),
    ("nevaren", "pericoloso", "peligroso", "dangerous"),
    ("varen", "sicuro", "seguro", "safe"),
    ("udoben", "comodo", "cómodo", "comfortable"),
    ("dolgočasen", "noioso", "aburrido", "boring"),
    ("zanimiv", "interessante", "interesante", "interesting"),
    ("prijazen", "gentile", "amable", "kind"),
    ("prijeten", "piacevole", "agradable", "pleasant"),
    ("resen", "serio", "serio", "serious"),
    ("glasen", "rumoroso", "ruidoso", "loud"),
    ("tiho", "silenzioso", "silencioso", "quiet"),
    ("lahek", "facile", "fácil", "easy"),
    ("težek", "difficile", "difícil", "difficult"),
    ("svetel", "luminoso", "luminoso", "bright"),
    ("temen", "scuro", "oscuro", "dark"),
    ("daljni", "lontano", "lejano", "far"),
    ("blizu", "vicino", "cerca", "near"),
    ("zgoden", "presto", "temprano", "early"),
    ("pozen", "tardo", "tarde", "late"),
    ("naprej", "avanti", "adelante", "forward"),
    ("nazaj", "indietro", "atrás", "back"),
    ("zgoraj", "sopra", "arriba", "above"),
    ("spodaj", "sotto", "abajo", "below"),
    ("notri", "dentro", "dentro", "inside"),
    ("zunaj", "fuori", "fuera", "outside"),
    ("mogočen", "potente", "poderoso", "powerful"),
    ("šibek", "debole", "débil", "weak"),
    ("dragocen", "prezioso", "valioso", "valuable"),
    ("uporaben", "utile", "útil", "useful"),
    ("neuporaben", "inutile", "inútil", "useless"),
    ("zabaven", "divertente", "divertido", "funny"),
    ("srečen", "felice", "feliz", "happy"),
    ("nesrečen", "infelice", "infeliz", "unhappy"),
    ("utrujen", "stanco", "cansado", "tired"),
    ("zaskrbljen", "preoccupato", "preocupado", "worried"),
    ("navdušen", "entusiasta", "entusiasmado", "excited"),
    ("zadovoljen", "soddisfatto", "satisfecho", "satisfied"),
    ("nezadovoljen", "insoddisfatto", "insatisfecho", "unsatisfied"),
    ("prijateljstvo", "amicizia", "amistad", "friendship"),
    ("družina", "famiglia", "familia", "family"),
    ("služba", "lavoro", "trabajo", "job"),
    ("dopust", "vacanza", "vacaciones", "holiday"),
    ("pomoč", "aiuto", "ayuda", "help"),
    ("vprašanje", "domanda", "pregunta", "question"),
    ("odgovor", "risposta", "respuesta", "answer"),
    ("rešitev", "soluzione", "solución", "solution"),
    ("problem", "problema", "problema", "problem"),
    ("priložnost", "opportunità", "oportunidad", "opportunity"),
    ("nevarnost", "pericolo", "peligro", "danger"),
    ("informacija", "informazione", "información", "information"),
    ("zgodovina", "storia", "historia", "history"),
    ("prihodnost", "futuro", "futuro", "future"),
    ("sedanjost", "presente", "presente", "present"),
    ("preteklost", "passato", "pasado", "past"),
    ("narava", "natura", "naturaleza", "nature"),
    ("mesto", "città", "ciudad", "city"),
    ("država", "paese", "país", "country"),
    ("okolje", "ambiente", "medio ambiente", "environment"),
    ("razlika", "differenza", "diferencia", "difference"),
    ("podobnost", "somiglianza", "semejanza", "similarity"),
    ("večina", "maggioranza", "mayoría", "majority"),
    ("manjšina", "minoranza", "minoría", "minority"),
    ("začetek", "inizio", "inicio", "beginning"),
    ("sredina", "mezzo", "mitad", "middle"),
    ("zgodba", "storia", "historia", "story"),
    ("pismo", "lettera", "carta", "letter"),
    ("besedilo", "testo", "texto", "text"),
    ("slovar", "dizionario", "diccionario", "dictionary"),
    ("članek", "articolo", "artículo", "article"),
    ("novica", "notizia", "noticia", "news"),
    ("časopis", "giornale", "periódico", "newspaper"),
    ("revija", "rivista", "revista", "magazine"),
    ("računalnik", "computer", "ordenador", "computer"),
    ("telefon", "telefono", "teléfono", "phone"),
    ("zaslon", "schermo", "pantalla", "screen"),
    ("tipkovnica", "tastiera", "teclado", "keyboard"),
    ("miška", "mouse", "ratón", "mouse"),
    ("internet", "internet", "internet", "internet"),
    ("geslo", "password", "contraseña", "password"),
    ("uporabnik", "utente", "usuario", "user"),
    ("program", "programma", "programa", "program"),
    ("sistem", "sistema", "sistema", "system"),
    ("nastavitve", "impostazioni", "ajustes", "settings"),
    ("datoteka", "file", "archivo", "file"),
    ("mapa", "cartella", "carpeta", "folder"),
    ("kamera", "telecamera", "cámara", "camera"),
    ("pogovor", "conversazione", "conversación", "conversation"),
    ("sestanek", "riunione", "reunión", "meeting"),
    ("predavanje", "lezione", "clase", "lecture"),
    ("vajenec", "apprendista", "aprendiz", "apprentice"),
    ("študent", "studente", "estudiante", "student"),
    ("učitelj", "insegnante", "profesor", "teacher"),
    ("direktor", "direttore", "director", "director"),
    ("zaposlen", "dipendente", "empleado", "employee"),
    ("kolektiv", "collettivo", "equipo", "team"),
    ("projekti", "progetti", "proyectos", "projects"),
    ("naloga", "compito", "tarea", "task"),
    ("rezultat", "risultato", "resultado", "result"),
    ("uspeh", "successo", "éxito", "success"),
    ("napaka", "errore", "error", "mistake"),
    ("izkušnja", "esperienza", "experiencia", "experience"),
    ("znanje", "conoscenza", "conocimiento", "knowledge"),
    ("spretnost", "abilità", "habilidad", "skill"),
    ("vpogled", "intuizione", "visión", "insight"),
    ("dogodek", "evento", "evento", "event"),
    ("srečanje", "incontro", "encuentro", "meeting"),
    ("praznik", "festa", "fiesta", "holiday"),
    ("darilo", "regalo", "regalo", "gift"),
    ("zdravje", "salute", "salud", "health"),
    ("bolezen", "malattia", "enfermedad", "illness"),
    ("zdravnik", "medico", "médico", "doctor"),
    ("bolnišnica", "ospedale", "hospital", "hospital"),
    ("zdravilo", "medicina", "medicamento", "medicine"),
    ("trgovina", "negozio", "tienda", "shop"),
    ("trgovalec", "commerciante", "comerciante", "trader"),
    ("stranka", "cliente", "cliente", "customer"),
    ("račun", "fattura", "factura", "invoice"),
    ("gotovina", "contanti", "efectivo", "cash"),
    ("bančnik", "banchiere", "banquero", "banker"),
    ("pogodba", "contratto", "contrato", "contract"),
    ("podpis", "firma", "firma", "signature"),
    ("pravilo", "regola", "regla", "rule"),
    ("zakon", "legge", "ley", "law"),
    ("svoboda", "libertà", "libertad", "freedom"),
    ("pravica", "diritto", "derecho", "right"),
    ("dolžnost", "dovere", "deber", "duty"),
    ("obveznost", "obbligo", "obligación", "obligation"),
    ("dogovor", "accordo", "acuerdo", "agreement"),
    ("povabilo", "invito", "invitación", "invitation"),
    ("odhod", "partenza", "salida", "departure"),
    ("prihod", "arrivo", "llegada", "arrival"),
]


# Mapa kategorij za uporabo v programu
CATEGORIES = {
    1: ("Glagoli", VERBS),
    2: ("Glagoli v spregatvah (sedanjik)", VERB_CONJ),
    3: ("Pridevniki", ADJECTIVES),
    4: ("Hrana", FOOD),
    5: ("Družina in sorodstvene vezi", FAMILY),
    6: ("Predlogi", PREPOSITIONS),
    7: ("Čas (dnevi, meseci, letni časi …)", TIME_WORDS),
    8: ("Različne pogoste besede", COMMON_WORDS),
}
